### ISSUE TITLE
"Couldn't find the requested file" on script

### ISSUE THREAD

**Issue by declider** [Om-Thorat/Spicetify-extensions#1]
I installed the extension from the marketplace, tried to run demo app, but nothing came to it.

I turned on the developer mode through the `spicetify enable-devtools` command, clicked on the links to the scripts in DOM (i have 4 installed extensions) - 3 out of 4 work (return the actual code), when I try to open the PlaybackApi script, this is returned:

```
Couldn't find the requested file /Unofficial-Playback-api/dist/playbackapi.js in Om-Thorat/Spicetify-extension.
```

Windows 10, textual and flask are installed, python 3.9.9
Spotify information

```
Spotify () для Windows (64-разрядная версия)
1.2.22.982.g794acc0a
Spicetify v2.24.2
Theme: marketplace
Extensions: volumePercentageWrapper.js, playOnYouTube.js, copytoclipboard.js, playbackapi.js
Custom apps: marketplace
xpui_2023-10-06_1696604276454_794acc0
cef_116.0.27+gd8c85ac+chromium-116.0.5845.190
```

**Comment by Om-Thorat** [comment]
Oops It was an issue with the `manifest.json` since i moved the proj to a diff repo and forgot to change it, zFixed it. Should work properly in a few hours now when cache is flushed in marketplace cdns.

**Comment by declider** [comment]
@Om-Thorat yes, it works now, thanks!
